services:
  # Database (MySQL)
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: init_db
      MYSQL_ROOT_PASSWORD: 3000676500
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-network

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    links:
     - mysql
    ports:
      - 3307:80
    networks:
      - mysql-network
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

# Networks
networks:
  mysql-network:
    name: mysql-network
    driver: bridge

# Volumes
volumes:
  mysqldata:
    driver: local
